====== Request for Comments: Supports finally keyword ======
  * Version: 1.0
  * Date: 2012/07/24
  * Author: Xinchen Hui <laruence.php.net>
  * Status: Under Discussion
  * First Published at: http://wiki.php.net/rfc/finally

===== Introduction =====
This RFC is try to introduce 'finally' support for exceptions

===== Proposal and Patch =====
The finally block always executes when the try block exits. This ensures that the finally block is executed even if an unexpected exception occurs. But finally is useful for more than just exception handling â€” it allows the programmer to avoid having cleanup code accidentally bypassed by a return, continue, or break. Putting cleanup code in a finally block is always a good practice, even when no exceptions are anticipated.

<code php>
<?php
   try {
     $fp = fopen("/tmp/1.php", "w");
     //error occurred
     throw new Exception($e);
   } catch (Exception $e) {
     
   } finally { 
     fclose($fp);
   }
</code>

the most confuse part is call "return in try/catch block",  in this case the finally block will still be called

<code php>
<?php
  try {
    return 2;
  } catch (Exception $e) {
  
  } finally {
    echo "this will be called\n";
  }
  //this will never be called
  echo "you can not see me";

</code>

the above script will outpu:
<code>
this will be called
//return int(2)
</code>
===== Changelog =====
  * 2012/07/24 Xinchen Hui: Initial version